### PR TITLE
Added new app shiny-certificate

### PR DESCRIPTION
**Pull request by royfrancis**
* Added R packages for app shiny-certificate
* Incremented version to 1.1
* Updated README

### CODE REVIEW

**Comment by nanjiangshu** [comment]
Looks good to me. Maybe you can also add the hyperlink in the `index.html` and `apps/index.html` for the new app.

**Comment by royfrancis** [comment]
Done!

**Comment by nanjiangshu** [comment]
Hi @royfrancis, I fixed a syntax error in the Dockerfile (adding backslash) but when compiling the docker image, I found this warning message: 
```Warning message:                                                                                   
package ‘ggtext’ is not available (for R version 3.6.1)  
```
What is the version of R you have used when developing the code?

**Comment by royfrancis** [comment]
Ah right, I am working with R 4.0. How do you handle this since your dockerfile starts from **rocker/shiny:3.6.1**?

**Comment by nanjiangshu** [comment]
Hi Roy, I have solved the problem by installing `ggtext` with `BiocManager`.

**Comment by royfrancis** [comment]
Novel solution! :D

**Pull request merged**
